FROM ccr.ccs.tencentyun.com/eqxiu/jre8
RUN	apk --update add libc6-compat ca-certificates wget openssl tzdata && \
		update-ca-certificates
RUN	cp /usr/share/zoneinfo/Asia/Shanghai /etc/localtime && \
		echo "Asia/Shanghai" > /etc/timezone
COPY entrypoint.sh /entrypoint.sh
